services:
  redis:
    image: redis:7-alpine
    container_name: vidbox-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --requirepass vidbox --appendonly yes --maxmemory-policy allkeys-lru
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  redis_data:
